export const dummy_data = [
  {
    GSTIN: "07AABCZ5840K1ZZ",
    "Legal Name of Bussiness": "Zomoto Private Limited",
    "GSTIN Status": "Active",
    "Consitution Bussiness": "Private Company",
    "Taxpayer Type": "Regular",
    "Date of Registration": "12-Dec-2023",
    "State Jurisdiction details": "100 Ward",
    "Center Jurisdiction details": "NA",
  },
  {
    GSTIN: "12ABCDE3456F1GH",
    "Legal Name of Bussiness": "ABC Corporation",
    "GSTIN Status": "Active",
    "Consitution Bussiness": "Public Limited Company",
    "Taxpayer Type": "Composition",
    "Date of Registration": "15-Jan-2023",
    "State Jurisdiction details": "75 Zone",
    "Center Jurisdiction details": "NA",
  },
  {
    GSTIN: "23FGHIJ4567K2LM",
    "Legal Name of Bussiness": "XYZ Enterprises Pvt Ltd",
    "GSTIN Status": "Inactive",
    "Consitution Bussiness": "Private Limited",
    "Taxpayer Type": "Regular",
    "Date of Registration": "20-Feb-2023",
    "State Jurisdiction details": "42 Division",
    "Center Jurisdiction details": "NA",
  },
  {
    GSTIN: "34KLMNO5678P3QR",
    "Legal Name of Bussiness": "LMN Innovations LLP",
    "GSTIN Status": "Active",
    "Consitution Bussiness": "Limited Liability Partnership",
    "Taxpayer Type": "Composition",
    "Date of Registration": "25-Mar-2023",
    "State Jurisdiction details": "60 Sector",
    "Center Jurisdiction details": "NA",
  },
  {
    GSTIN: "45RSTUV7890Q4WX",
    "Legal Name of Bussiness": "PQR Solutions Pvt Ltd",
    "GSTIN Status": "Active",
    "Consitution Bussiness": "Private Company",
    "Taxpayer Type": "Regular",
    "Date of Registration": "30-Apr-2023",
    "State Jurisdiction details": "28 Block",
    "Center Jurisdiction details": "NA",
  },
  {
    GSTIN: "56WXYZ1234U5AB",
    "Legal Name of Bussiness": "WXYZ Tech LLP",
    "GSTIN Status": "Active",
    "Consitution Bussiness": "Limited Liability Partnership",
    "Taxpayer Type": "Composition",
    "Date of Registration": "05-May-2023",
    "State Jurisdiction details": "15 District",
    "Center Jurisdiction details": "NA",
  },
  {
    GSTIN: "67CDEFG5678V6HI",
    "Legal Name of Bussiness": "HIJ Services Pvt Ltd",
    "GSTIN Status": "Active",
    "Consitution Bussiness": "Private Company",
    "Taxpayer Type": "Regular",
    "Date of Registration": "10-Jun-2023",
    "State Jurisdiction details": "33 Wing",
    "Center Jurisdiction details": "NA",
  },
  {
    GSTIN: "78IJKL8901X7MN",
    "Legal Name of Bussiness": "MNO Innovations LLP",
    "GSTIN Status": "Inactive",
    "Consitution Bussiness": "Limited Liability Partnership",
    "Taxpayer Type": "Composition",
    "Date of Registration": "15-Jul-2023",
    "State Jurisdiction details": "48 Zone",
    "Center Jurisdiction details": "NA",
  },
  {
    GSTIN: "89OPQR2345Y8ST",
    "Legal Name of Bussiness": "PQR Solutions Pvt Ltd",
    "GSTIN Status": "Active",
    "Consitution Bussiness": "Private Company",
    "Taxpayer Type": "Regular",
    "Date of Registration": "20-Aug-2023",
    "State Jurisdiction details": "22 Division",
    "Center Jurisdiction details": "NA",
  },
  {
    GSTIN: "90UVWX4567Z9AB",
    "Legal Name of Bussiness": "UVW Tech LLP",
    "GSTIN Status": "Active",
    "Consitution Bussiness": "Limited Liability Partnership",
    "Taxpayer Type": "Composition",
    "Date of Registration": "25-Sep-2023",
    "State Jurisdiction details": "55 Sector",
    "Center Jurisdiction details": "NA",
  },
];
